# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
sudo: false

r:
    - oldrel
    - release
    - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
